server:
  port: 7070

spring:
  datasource:
#    url: jdbc:oracle:thin:@//oracle-db:1521/XE
    url: jdbc:oracle:thin:@localhost:1521/XE
    username: APPLICATION_DEMO
    password: App#12345a
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
  sql:
    init:
      mode: never

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /v1/swagger-ui.html
    csrf:
      enabled: false
    persist-authorization: true
  paths-to-match: /v1/**

sftp:
#  host: sftp         # inside Docker: service name; locally: localhost
  host: localhost
#  port: 22           # inside Docker; locally use 2222
  port: 2222
  username: foo
  password: pass
  remote-dir: /upload
  connect-timeout-ms: 10000
  strict-host-key-checking: false