server:
  port: 8081

spring:
#  datasource:
#    url: jdbc:oracle:thin:@localhost:1521/XE
#    username: APPLICATION_DEMO
#    password: apppassword
#    driver-class-name: oracle.jdbc.OracleDriver
  datasource:
    url: jdbc:oracle:thin:@oracle-db:1521/XE
    username: system
    password: oracle
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.OracleDialect  # or Oracle12cDialect
    properties:
      hibernate.temp.use_jdbc_metadata_defaults: false
#    defer-datasource-initialization: true
  sql:
    init:
      mode: always

camunda:
  bpm:
    authorization:
      enabled: false
  webapp:
    index-redirect-enabled: false
camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  authorization:
    enabled: false

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /v1/swagger-ui.html
    csrf:
      enabled: false
    persist-authorization: true
  paths-to-match: /v1/**

sftp:
  host: localhost
  port: 2222
  username: foo
  password: pass
  remote-dir: /home/foo/upload
  connect-timeout-ms: 8000
  session-timeout-ms: 10000
sync:
  sftp:
    batch-size: 100
    enabled: true
    cron: "0 */1 * * * *"         # every minute (optional)
