server:
  port: 8081

spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521/XEPDB1
    username: APPLICATION_DEMO
    password: apppassword
    driver-class-name: oracle.jdbc.OracleDriver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

camunda:
  bpm:
    authorization:
      enabled: false
  webapp:
    index-redirect-enabled: false
camunda.bpm:
  admin-user:
    id: demo
    password: demo
    firstName: Demo
  authorization:
    enabled: false

springdoc:
  api-docs:
    path: /v1/api-docs
  swagger-ui:
    path: /v1/swagger-ui.html
    csrf:
      enabled: false
    persist-authorization: true
  paths-to-match: /v1/**
